### ISSUE TITLE
Change returned value of loopReminder to false if set to "None" for consistency.

### ISSUE THREAD

**Issue by michtio** [percipioglobal/craft-timeloop#26]
currently the graphQL query returns the data as follows:

```
"loopPeriod": "daily",
"loopReminder": "None",
"loopStart": "2021-05-07T08:30:00+00:00",
"loopEnd": false,
```

When `loopReminder` is set to `"None"` it makes sense to output `false` to stay consistent with `loopEnd`

**Comment by cookie10codes** [comment]
We will implement #23 instead
