### ISSUE TITLE
Dates omitted/appearing outside of date range

### ISSUE THREAD

**Issue by mjniland1** [percipioglobal/craft-timeloop#51]
I'm trying out timeloop for a project but I'm experiencing some strange behavior. Here are my settings:

Start Date: 8/9/22
End Date: 16/9/22
Frequency: Every Week
Interval: Every 1 week on Saturday

I'm using the following loop to get future dates:

{% for date in entry.timeloop.dates %}
   {{ date | date('d/m/y') }}
{% endfor %}

In my mind, these settings should return: 10/9/22 but my loop outputs 17/9/22. It omits the correct date and returns one outside the start/end date range. 

Craft Version: Craft Pro 4.2.3
PHP: 8.0.8
Timeloop: 4.0.1

**Comment by jt-systems** [comment]
Hi @mjniland1 - I would agree that expected behaviour is not correct on this. We'll jump on and update this - expect an update early next week 👍

**Comment by cookie10codes** [comment]
Hi @mjniland1,

Thanks for raising the issue, my apologies it occurred. A release with a bug fix just went out. Let me know if this solves your issue.
