### ISSUE TITLE
How does this work with twig queries

### ISSUE THREAD

**Issue by stenvdb** [percipioglobal/craft-timeloop#52]
Can you help me on the following:

I want a recurring entry for say, every week for the next 3 months. I have a twig template set up to go through every month (like a calendar). I want to get the entries in every month based on the timeloop field, how would I do this?

So I basicly want to query for entries where the timeloop contains dates between a certain start and end date.

**Comment by cookie10codes** [comment]
Hi @stenvdb,

Thanks for opening the issue. We've added this as a feature request to our new release. More info on docs can be found in the readme https://github.com/percipioglobal/craft-timeloop/tree/4.1.0#get-entries-between-certain-dates

Let me know if things are unclear, you can reply in this closed thread.

Have a great day
